import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../src/organisms/Header";
import { Container } from "@chakra-ui/react";
import TitleInput from "../src/molucules/input/TitleInput";
import DetailTextarea from "../src/molucules/input/DetailTextarea";
import Title from "../src/atoms/text/Title";

const NewTodo = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Container maxWidth="800px" marginTop="100px">
          <Title children="New Todo" />
          <TitleInput />
          <DetailTextarea />
        </Container>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
};

export default NewTodo;
